/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as CertificateRouteImport } from './routes/certificate'
import { Route as UserRouteRouteImport } from './routes/user/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as UserTransactionsIndexRouteImport } from './routes/user/transactions/index'
import { Route as UserRequestsIndexRouteImport } from './routes/user/requests/index'
import { Route as AdminVetIndexRouteImport } from './routes/admin/vet/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminTransactionsIndexRouteImport } from './routes/admin/transactions/index'
import { Route as AdminTemplatesIndexRouteImport } from './routes/admin/templates/index'
import { Route as AdminRolesIndexRouteImport } from './routes/admin/roles/index'
import { Route as AdminRequestsIndexRouteImport } from './routes/admin/requests/index'
import { Route as AdminFacultyIndexRouteImport } from './routes/admin/faculty/index'
import { Route as AdminDocumentsIndexRouteImport } from './routes/admin/documents/index'
import { Route as AdminDepartmentIndexRouteImport } from './routes/admin/department/index'
import { Route as AdminComboIndexRouteImport } from './routes/admin/combo/index'
import { Route as AdminChainIndexRouteImport } from './routes/admin/chain/index'
import { Route as AdminAdminsIndexRouteImport } from './routes/admin/admins/index'
import { Route as UserRequestsIdRouteImport } from './routes/user/requests/id'
import { Route as AdminTemplatesIdRouteImport } from './routes/admin/templates/$id'
import { Route as AdminTemplatesComponentsIndexRouteImport } from './routes/admin/templates/components/index'
import { Route as AdminTemplatesComponentsIdRouteImport } from './routes/admin/templates/components/$id'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateRoute = CertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRouteRoute = UserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UserTransactionsIndexRoute = UserTransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserRequestsIndexRoute = UserRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => UserRouteRoute,
} as any)
const AdminVetIndexRoute = AdminVetIndexRouteImport.update({
  id: '/vet/',
  path: '/vet/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTransactionsIndexRoute = AdminTransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTemplatesIndexRoute = AdminTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRolesIndexRoute = AdminRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRequestsIndexRoute = AdminRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFacultyIndexRoute = AdminFacultyIndexRouteImport.update({
  id: '/faculty/',
  path: '/faculty/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDocumentsIndexRoute = AdminDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDepartmentIndexRoute = AdminDepartmentIndexRouteImport.update({
  id: '/department/',
  path: '/department/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminComboIndexRoute = AdminComboIndexRouteImport.update({
  id: '/combo/',
  path: '/combo/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminChainIndexRoute = AdminChainIndexRouteImport.update({
  id: '/chain/',
  path: '/chain/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminsIndexRoute = AdminAdminsIndexRouteImport.update({
  id: '/admins/',
  path: '/admins/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const UserRequestsIdRoute = UserRequestsIdRouteImport.update({
  id: '/requests/id',
  path: '/requests/id',
  getParentRoute: () => UserRouteRoute,
} as any)
const AdminTemplatesIdRoute = AdminTemplatesIdRouteImport.update({
  id: '/templates/$id',
  path: '/templates/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTemplatesComponentsIndexRoute =
  AdminTemplatesComponentsIndexRouteImport.update({
    id: '/templates/components/',
    path: '/templates/components/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminTemplatesComponentsIdRoute =
  AdminTemplatesComponentsIdRouteImport.update({
    id: '/templates/components/$id',
    path: '/templates/components/$id',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/certificate': typeof CertificateRoute
  '/verify': typeof VerifyRoute
  '/auth/login': typeof AuthLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/user/': typeof UserIndexRoute
  '/admin/templates/$id': typeof AdminTemplatesIdRoute
  '/user/requests/id': typeof UserRequestsIdRoute
  '/admin/admins': typeof AdminAdminsIndexRoute
  '/admin/chain': typeof AdminChainIndexRoute
  '/admin/combo': typeof AdminComboIndexRoute
  '/admin/department': typeof AdminDepartmentIndexRoute
  '/admin/documents': typeof AdminDocumentsIndexRoute
  '/admin/faculty': typeof AdminFacultyIndexRoute
  '/admin/requests': typeof AdminRequestsIndexRoute
  '/admin/roles': typeof AdminRolesIndexRoute
  '/admin/templates': typeof AdminTemplatesIndexRoute
  '/admin/transactions': typeof AdminTransactionsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/vet': typeof AdminVetIndexRoute
  '/user/requests': typeof UserRequestsIndexRoute
  '/user/transactions': typeof UserTransactionsIndexRoute
  '/admin/templates/components/$id': typeof AdminTemplatesComponentsIdRoute
  '/admin/templates/components': typeof AdminTemplatesComponentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certificate': typeof CertificateRoute
  '/verify': typeof VerifyRoute
  '/auth/login': typeof AuthLoginRoute
  '/admin': typeof AdminIndexRoute
  '/user': typeof UserIndexRoute
  '/admin/templates/$id': typeof AdminTemplatesIdRoute
  '/user/requests/id': typeof UserRequestsIdRoute
  '/admin/admins': typeof AdminAdminsIndexRoute
  '/admin/chain': typeof AdminChainIndexRoute
  '/admin/combo': typeof AdminComboIndexRoute
  '/admin/department': typeof AdminDepartmentIndexRoute
  '/admin/documents': typeof AdminDocumentsIndexRoute
  '/admin/faculty': typeof AdminFacultyIndexRoute
  '/admin/requests': typeof AdminRequestsIndexRoute
  '/admin/roles': typeof AdminRolesIndexRoute
  '/admin/templates': typeof AdminTemplatesIndexRoute
  '/admin/transactions': typeof AdminTransactionsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/vet': typeof AdminVetIndexRoute
  '/user/requests': typeof UserRequestsIndexRoute
  '/user/transactions': typeof UserTransactionsIndexRoute
  '/admin/templates/components/$id': typeof AdminTemplatesComponentsIdRoute
  '/admin/templates/components': typeof AdminTemplatesComponentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/certificate': typeof CertificateRoute
  '/verify': typeof VerifyRoute
  '/auth/login': typeof AuthLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/user/': typeof UserIndexRoute
  '/admin/templates/$id': typeof AdminTemplatesIdRoute
  '/user/requests/id': typeof UserRequestsIdRoute
  '/admin/admins/': typeof AdminAdminsIndexRoute
  '/admin/chain/': typeof AdminChainIndexRoute
  '/admin/combo/': typeof AdminComboIndexRoute
  '/admin/department/': typeof AdminDepartmentIndexRoute
  '/admin/documents/': typeof AdminDocumentsIndexRoute
  '/admin/faculty/': typeof AdminFacultyIndexRoute
  '/admin/requests/': typeof AdminRequestsIndexRoute
  '/admin/roles/': typeof AdminRolesIndexRoute
  '/admin/templates/': typeof AdminTemplatesIndexRoute
  '/admin/transactions/': typeof AdminTransactionsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/vet/': typeof AdminVetIndexRoute
  '/user/requests/': typeof UserRequestsIndexRoute
  '/user/transactions/': typeof UserTransactionsIndexRoute
  '/admin/templates/components/$id': typeof AdminTemplatesComponentsIdRoute
  '/admin/templates/components/': typeof AdminTemplatesComponentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/user'
    | '/certificate'
    | '/verify'
    | '/auth/login'
    | '/admin/'
    | '/user/'
    | '/admin/templates/$id'
    | '/user/requests/id'
    | '/admin/admins'
    | '/admin/chain'
    | '/admin/combo'
    | '/admin/department'
    | '/admin/documents'
    | '/admin/faculty'
    | '/admin/requests'
    | '/admin/roles'
    | '/admin/templates'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/vet'
    | '/user/requests'
    | '/user/transactions'
    | '/admin/templates/components/$id'
    | '/admin/templates/components'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/certificate'
    | '/verify'
    | '/auth/login'
    | '/admin'
    | '/user'
    | '/admin/templates/$id'
    | '/user/requests/id'
    | '/admin/admins'
    | '/admin/chain'
    | '/admin/combo'
    | '/admin/department'
    | '/admin/documents'
    | '/admin/faculty'
    | '/admin/requests'
    | '/admin/roles'
    | '/admin/templates'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/vet'
    | '/user/requests'
    | '/user/transactions'
    | '/admin/templates/components/$id'
    | '/admin/templates/components'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/user'
    | '/certificate'
    | '/verify'
    | '/auth/login'
    | '/admin/'
    | '/user/'
    | '/admin/templates/$id'
    | '/user/requests/id'
    | '/admin/admins/'
    | '/admin/chain/'
    | '/admin/combo/'
    | '/admin/department/'
    | '/admin/documents/'
    | '/admin/faculty/'
    | '/admin/requests/'
    | '/admin/roles/'
    | '/admin/templates/'
    | '/admin/transactions/'
    | '/admin/users/'
    | '/admin/vet/'
    | '/user/requests/'
    | '/user/transactions/'
    | '/admin/templates/components/$id'
    | '/admin/templates/components/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  UserRouteRoute: typeof UserRouteRouteWithChildren
  CertificateRoute: typeof CertificateRoute
  VerifyRoute: typeof VerifyRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate': {
      id: '/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof CertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/transactions/': {
      id: '/user/transactions/'
      path: '/transactions'
      fullPath: '/user/transactions'
      preLoaderRoute: typeof UserTransactionsIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/requests/': {
      id: '/user/requests/'
      path: '/requests'
      fullPath: '/user/requests'
      preLoaderRoute: typeof UserRequestsIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/admin/vet/': {
      id: '/admin/vet/'
      path: '/vet'
      fullPath: '/admin/vet'
      preLoaderRoute: typeof AdminVetIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/transactions/': {
      id: '/admin/transactions/'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/templates/': {
      id: '/admin/templates/'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/roles/': {
      id: '/admin/roles/'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/requests/': {
      id: '/admin/requests/'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/faculty/': {
      id: '/admin/faculty/'
      path: '/faculty'
      fullPath: '/admin/faculty'
      preLoaderRoute: typeof AdminFacultyIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/documents/': {
      id: '/admin/documents/'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/department/': {
      id: '/admin/department/'
      path: '/department'
      fullPath: '/admin/department'
      preLoaderRoute: typeof AdminDepartmentIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/combo/': {
      id: '/admin/combo/'
      path: '/combo'
      fullPath: '/admin/combo'
      preLoaderRoute: typeof AdminComboIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/chain/': {
      id: '/admin/chain/'
      path: '/chain'
      fullPath: '/admin/chain'
      preLoaderRoute: typeof AdminChainIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/admins/': {
      id: '/admin/admins/'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/user/requests/id': {
      id: '/user/requests/id'
      path: '/requests/id'
      fullPath: '/user/requests/id'
      preLoaderRoute: typeof UserRequestsIdRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/admin/templates/$id': {
      id: '/admin/templates/$id'
      path: '/templates/$id'
      fullPath: '/admin/templates/$id'
      preLoaderRoute: typeof AdminTemplatesIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/templates/components/': {
      id: '/admin/templates/components/'
      path: '/templates/components'
      fullPath: '/admin/templates/components'
      preLoaderRoute: typeof AdminTemplatesComponentsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/templates/components/$id': {
      id: '/admin/templates/components/$id'
      path: '/templates/components/$id'
      fullPath: '/admin/templates/components/$id'
      preLoaderRoute: typeof AdminTemplatesComponentsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminTemplatesIdRoute: typeof AdminTemplatesIdRoute
  AdminAdminsIndexRoute: typeof AdminAdminsIndexRoute
  AdminChainIndexRoute: typeof AdminChainIndexRoute
  AdminComboIndexRoute: typeof AdminComboIndexRoute
  AdminDepartmentIndexRoute: typeof AdminDepartmentIndexRoute
  AdminDocumentsIndexRoute: typeof AdminDocumentsIndexRoute
  AdminFacultyIndexRoute: typeof AdminFacultyIndexRoute
  AdminRequestsIndexRoute: typeof AdminRequestsIndexRoute
  AdminRolesIndexRoute: typeof AdminRolesIndexRoute
  AdminTemplatesIndexRoute: typeof AdminTemplatesIndexRoute
  AdminTransactionsIndexRoute: typeof AdminTransactionsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminVetIndexRoute: typeof AdminVetIndexRoute
  AdminTemplatesComponentsIdRoute: typeof AdminTemplatesComponentsIdRoute
  AdminTemplatesComponentsIndexRoute: typeof AdminTemplatesComponentsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminTemplatesIdRoute: AdminTemplatesIdRoute,
  AdminAdminsIndexRoute: AdminAdminsIndexRoute,
  AdminChainIndexRoute: AdminChainIndexRoute,
  AdminComboIndexRoute: AdminComboIndexRoute,
  AdminDepartmentIndexRoute: AdminDepartmentIndexRoute,
  AdminDocumentsIndexRoute: AdminDocumentsIndexRoute,
  AdminFacultyIndexRoute: AdminFacultyIndexRoute,
  AdminRequestsIndexRoute: AdminRequestsIndexRoute,
  AdminRolesIndexRoute: AdminRolesIndexRoute,
  AdminTemplatesIndexRoute: AdminTemplatesIndexRoute,
  AdminTransactionsIndexRoute: AdminTransactionsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminVetIndexRoute: AdminVetIndexRoute,
  AdminTemplatesComponentsIdRoute: AdminTemplatesComponentsIdRoute,
  AdminTemplatesComponentsIndexRoute: AdminTemplatesComponentsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface UserRouteRouteChildren {
  UserIndexRoute: typeof UserIndexRoute
  UserRequestsIdRoute: typeof UserRequestsIdRoute
  UserRequestsIndexRoute: typeof UserRequestsIndexRoute
  UserTransactionsIndexRoute: typeof UserTransactionsIndexRoute
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserIndexRoute: UserIndexRoute,
  UserRequestsIdRoute: UserRequestsIdRoute,
  UserRequestsIndexRoute: UserRequestsIndexRoute,
  UserTransactionsIndexRoute: UserTransactionsIndexRoute,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  UserRouteRoute: UserRouteRouteWithChildren,
  CertificateRoute: CertificateRoute,
  VerifyRoute: VerifyRoute,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
